services:
  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    container_name: trip-sheet-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - trip-sheet-network

  # mysql:
  #   image: mysql:8
  #   restart: always
  #   container_name: mysql-trip-sheet
  #   env_file:
  #     - .env
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - trip-sheet-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD --silent"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"      
  
  trip-sheet-be:
    build: .
    restart: always
    container_name: trip-sheet-be
    env_file:
      - .env
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      redis:
        condition: service_healthy
    # depends_on:
    #   mysql:  
    #     condition: service_healthy
    networks:
      - trip-sheet-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  trip-sheet-network:
    driver: bridge
