package com.example.trip_sheet_backend.dtos.PurchaseOrderDtos;

import java.math.BigDecimal;
import java.util.UUID;
import java.util.List;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PurchaseOrderUpdateRequestDTO {
  private String orderNumber;
  private String documentType;
  private String currencyCode;
  private Long documentDate;
  private Long dueDate;
  private Long billingPeriodStart;
  private Long billingPeriodEnd;
  private String billToName;
  private String billToCode;
  private String billToGstin;
  private String billToAddress;
  private String supplierName;
  private String supplierPhone;
  private String supplierAddress;
  private Integer lineItemCount;
  private String lineItemsSnapshot;
  private UUID tripSummaryId;
  private List<PurchaseOrderAllocationRequestDTO> allocations;
  private com.example.trip_sheet_backend.models.PurchaseOrder.PurchaseOrderStatus status;
  private Long garageStartTime;
  private Long garageEndTime;
  private Long tripStartTime;
  private Long tripStartKmOdo;
  private Long tripStartKmOdoImage;
  private Long tripEndTime;
  private Long tripEndKmOdo;
  private Long tripEndKmOdoImage;
  private Long tripDuration;
  private Long tripDistance;
  private Long tripExtraKmOdo;
  private Long tripExtraKm;
  private Long tripExtraHr;
  private Long tripStartGPSKM;
  private Long tripEndGPSKM;
  private Long tripGPSDuration;
  private Long tripGPSDistance;
  private Double dispatchLat;
  private Double dispatchLng;
  private Double arrivedLat;
  private Double arrivedLng;
  private Double tripStartLat;
  private Double tripStartLng;
  private Double tripEndLat;
  private Double tripEndLng;
  private Double garageEndLat;
  private Double garageEndLng;
  private String tripCalculationFieldName;
  private String extraHrCalculationFieldName;
  private String extraKmCalculationFieldName;
  private String rateCardPackageName;
  private BigDecimal baseFareAmount;
  private BigDecimal baseFareQty;
  private BigDecimal baseFareTotal;
  private BigDecimal extraKmChargeAmount;
  private BigDecimal extraKmQty;
  private BigDecimal extraKmTotal;
  private BigDecimal extraHrChargeAmount;
  private BigDecimal extraHrQty;
  private BigDecimal extraHrTotal;
  private BigDecimal dailyAllowanceChargeAmount;
  private BigDecimal dailyAllowanceQty;
  private BigDecimal dailyAllowanceTotal;
  private BigDecimal earlyAllowanceChargeAmount;
  private BigDecimal earlyAllowanceQty;
  private BigDecimal earlyAllowanceTotal;
  private BigDecimal lateAllowanceChargeAmount;
  private BigDecimal lateAllowanceQty;
  private BigDecimal lateAllowanceTotal;
  private BigDecimal hourlyAllowanceChargeAmount;
  private BigDecimal hourlyAllowanceQty;
  private BigDecimal hourlyAllowanceTotal;
  private BigDecimal tollChargeAmount;
  private BigDecimal tollQty;
  private BigDecimal tollTotal;
  private BigDecimal parkingChargeAmount;
  private BigDecimal parkingQty;
  private BigDecimal parkingTotal;
  private BigDecimal otherChargeAmount;
  private BigDecimal otherQty;
  private BigDecimal otherTotal;
  private BigDecimal taxableSubTotal;
  private BigDecimal gstPercentage;
  private BigDecimal gstAmount;
  private BigDecimal cgstPercentage;
  private BigDecimal cgstAmount;
  private BigDecimal sgstPercentage;
  private BigDecimal sgstAmount;
  private BigDecimal igstPercentage;
  private BigDecimal igstAmount;
  private BigDecimal taxableTotalWithGst;
  private BigDecimal nonTaxableTotal;
  private BigDecimal roundOffAmount;
  private BigDecimal totalAmount;
  private String notes;
}
